FROM eclipse-temurin:11-jre

ENV IGNIFYR_HOME /usr/local/ignifyr
RUN mkdir -p "$IGNIFYR_HOME"
WORKDIR $IGNIFYR_HOME

COPY ./ignifyr-engine/target/ignifyr-engine-standalone.jar .
COPY ./docker/engine/docker-entrypoint.sh .
RUN chmod +x docker-entrypoint.sh

ENTRYPOINT ["./docker-entrypoint.sh"]
