# Stage 0
FROM maven:3.6-openjdk-11 AS builder

ENV IGNIFYR_HOME /usr/local/ignifyr
RUN mkdir -p "$IGNIFYR_HOME"
WORKDIR $IGNIFYR_HOME

COPY . ./

# Build without running the unit and integration tests
RUN mvn package -Pxtest

# Stage 1
FROM openjdk:11-jre-slim

ENV IGNIFYR_HOME /usr/local/ignifyr
RUN mkdir -p "$IGNIFYR_HOME"
WORKDIR $IGNIFYR_HOME

COPY --from=builder $IGNIFYR_HOME/ignifyr-cli/target/ignifyr-engine-standalone.jar .

COPY docker/engine/docker-entrypoint.sh .
RUN chmod +x docker-entrypoint.sh

ENTRYPOINT ["./docker-entrypoint.sh"]
