version: '3.9'
services:
  ignifyr-server:
    image: srdc/ignifyr-server:latest
    container_name: ignifyr-server
    hostname: ignifyr-server
    environment:
      - FHIR_DEFINITIONS_ENDPOINT=http://onfhir:8080/fhir
      - FHIR_REPO_URL=http://onfhir:8080/fhir
      - APP_CONF_FILE=/usr/local/ignifyr/conf/docker/ignifyr-server.conf
      - FLUENT_HOST=fluentd
      - CONTEXT_PATH=conf
    ports:
      - "8085:8085"
    networks:
      - ignifyr-network
    volumes:
      - './data-integration-suite:/usr/local/ignifyr/conf'
      - './ignifyr-docker-logs:/usr/local/ignifyr/logs'
  ignifyr-web:
    image: docker.srdc.com.tr/srdc/tofhir-web:latest
    container_name: ignifyr-web
    ports:
      - "8087:80"
    networks:
      - ignifyr-network
 # Elasticsearch, Fluentd and Kibana stack for mapping job log management
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.19
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - ignifyr-network
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  fluentd:
    build: ./fluentd
    container_name: fluentd
    image: docker.srdc.com.tr/srdc/ignifyr-fluentd:latest
    environment:
      - FORWARD_PORT=24224
      - HOST=elasticsearch
      - PORT=9200
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - ignifyr-network
  kibana:
    build:
      context: ./kibana
      dockerfile: ./Dockerfile
    image: docker.srdc.com.tr/srdc/ignifyr-kibana:latest
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - ignifyr-network
    depends_on:
      - elasticsearch
networks:
  ignifyr-network:
    name: onfhir-network
    external: true
volumes:
  elasticsearch_data:
    driver: local